import type { Metadata } from 'next'
import LegalPage from '@/components/legal/LegalPage'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'How Playchessify handles your data — wallet addresses, profiles, gameplay, and the third parties involved.',
  alternates: { canonical: '/privacy' },
}

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" updated="23 July 2026">
      <p>
        This Privacy Policy explains what information Playchessify (&ldquo;we&rdquo;,
        &ldquo;us&rdquo;) collects, how we use it, and who we share it with when you use our website,
        applications, and on-chain chess protocol (the &ldquo;Service&rdquo;). Playchessify is
        non-custodial and blockchain-based, so some of your activity is inherently public and
        permanent — please read the section on on-chain data carefully.
      </p>

      <h2>1. Information we collect</h2>
      <h3>Information you provide</h3>
      <ul>
        <li>
          <strong>Authentication details.</strong> When you sign in, our authentication provider
          (Privy) processes the login method you choose — for example an email address or a social
          account — and provisions your wallet. We receive the resulting wallet address and basic
          account status.
        </li>
        <li>
          <strong>Profile information.</strong> If you claim a profile, we store the username, display
          name, and short bio you choose.
        </li>
      </ul>
      <h3>Information created through gameplay</h3>
      <ul>
        <li>
          <strong>Wallet address.</strong> Your on-chain address is your identity across the Service.
        </li>
        <li>
          <strong>Game data.</strong> Moves, results, wagers, ratings, win/play streaks, and match
          history — used to run matches, settle results, and power leaderboards and profiles.
        </li>
        <li>
          <strong>AI coach interactions.</strong> When you request a coaching explanation, the board
          position and derived game facts for that moment are sent to a language-model provider to
          generate the lesson.
        </li>
      </ul>
      <h3>Information collected automatically</h3>
      <ul>
        <li>
          <strong>Technical data.</strong> Standard server and infrastructure logs (such as request
          metadata) generated by our hosting and storage providers, used for security, rate-limiting,
          and debugging.
        </li>
        <li>
          <strong>Local storage.</strong> We store settings, your session, and single-player game
          progress in your browser&rsquo;s local storage. See &ldquo;Cookies and local
          storage&rdquo; below.
        </li>
      </ul>

      <h2>2. On-chain data is public and permanent</h2>
      <p>
        Matches, wagers, results, and token transfers are recorded on the Celo blockchain. This data
        is <strong>public, immutable, and permanent</strong> — it is visible to anyone, associated
        with your wallet address, and <strong>cannot be edited or deleted</strong> by us or by you.
        Do not use the Service if you are not comfortable with this. Anything published to the
        blockchain is outside our ability to remove.
      </p>

      <h2>3. How we use your information</h2>
      <ul>
        <li>to operate matches, validate moves, and settle results on-chain;</li>
        <li>to maintain profiles, ratings, streaks, leaderboards, and match history;</li>
        <li>to generate AI coaching lessons you request;</li>
        <li>to sponsor gas and provision faucet tokens where offered;</li>
        <li>to secure the Service, prevent abuse, enforce fair play, and debug issues; and</li>
        <li>to comply with applicable law.</li>
      </ul>
      <p>We do not sell your personal information.</p>

      <h2>4. Service providers we share data with</h2>
      <p>
        We use trusted third parties to run the Service. They process data only to provide their
        service to us:
      </p>
      <ul>
        <li><strong>Privy</strong> — authentication and wallet infrastructure.</li>
        <li><strong>Upstash (Redis)</strong> — storage for profiles, move history, streaks, and caching.</li>
        <li><strong>Pimlico</strong> — account-abstraction bundler/paymaster for smart-wallet transactions.</li>
        <li>
          <strong>Language-model providers</strong> (which may include NVIDIA, Google, and Groq) —
          to generate AI coaching explanations from board positions.
        </li>
        <li><strong>Vercel</strong> — website and application hosting.</li>
        <li><strong>The Celo network</strong> — the public blockchain that records matches and settlements.</li>
      </ul>
      <p>
        Each provider has its own privacy practices. We may also disclose information if required by
        law or to protect the rights, safety, and integrity of the Service.
      </p>

      <h2>5. Cookies and local storage</h2>
      <p>
        We do not use advertising or tracking cookies. We rely on your browser&rsquo;s local and
        session storage to keep you signed in (via Privy), remember your settings (such as board
        theme and sound), and save single-player game progress. You can clear this at any time
        through your browser, though doing so will sign you out and reset local preferences.
      </p>

      <h2>6. Data retention</h2>
      <ul>
        <li>
          <strong>Move history</strong> stored in our relay is kept for up to 30 days after a game,
          then automatically expires.
        </li>
        <li>
          <strong>Profile, rating, and streak data</strong> is retained while your profile exists or
          until you ask us to remove it.
        </li>
        <li>
          <strong>On-chain data</strong> is permanent and cannot be deleted (see Section 2).
        </li>
      </ul>

      <h2>7. Your choices and rights</h2>
      <p>
        You may update your profile details in the app, or contact us to request access to or
        deletion of off-chain personal data we hold about you. Note that we cannot alter or remove
        anything recorded on the blockchain, and some data must be retained for security and
        legal reasons.
      </p>

      <h2>8. Children</h2>
      <p>
        The Service is not intended for anyone under 18, and we do not knowingly collect information
        from children. If you believe a minor has used the Service, please contact us.
      </p>

      <h2>9. Security</h2>
      <p>
        We take reasonable measures to protect the data we hold, but no system is perfectly secure.
        Because the Service is non-custodial, the security of your wallet and private keys is your
        responsibility.
      </p>

      <h2>10. International data transfers</h2>
      <p>
        Our providers may process and store data in countries other than yours. By using the Service
        you consent to such transfers, which are carried out with appropriate safeguards where
        required.
      </p>

      <h2>11. Changes to this policy</h2>
      <p>
        We may update this Privacy Policy from time to time. Material changes will be reflected by the
        &ldquo;Last updated&rdquo; date above. Your continued use of the Service after changes take
        effect constitutes acceptance.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions or requests about your privacy? Reach us at{' '}
        <a href="mailto:privacy@playchessify.xyz">privacy@playchessify.xyz</a>.
      </p>
    </LegalPage>
  )
}
